version: '3.8'
services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: autobook-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: autobook
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./autobook_dump.sql:/docker-entrypoint-initdb.d/01-dump.sql

volumes:
  mysql-data: